# Todos os campos do formulario, na ordem em que aparecem na ficha
FIELDS = [
    "nome_produtor", "cpf", "data_nascimento", "telefone", "dap_caf",
    "nome_propriedade", "municipio", "comunidade", "car", "latitude", "longitude",
    "assistido_ateg", "tecnico_responsavel", "foto_produtor",

    "membros_residentes", "sucessao_familiar", "mao_obra", "fonte_renda",
    "fonte_agua", "seguranca_hidrica",

    "area_leite", "volume_diario", "vacas_lactacao", "vacas_secas",
    "novilhas", "touros", "produtividade_media", "destino_producao",
    "composicao_genetica", "grau_girolando",

    "curral_ordenha", "tipo_ordenha", "higiene_ordenha", "refrigeracao_leite",
    "capacidade_tanque", "tronco_contencao", "obs_infraestrutura",

    "silagem", "estoque_seca", "palma_forrageira", "area_palma",
    "capineira", "area_capineira", "suplementacao", "sal_mineral",
    "agua_bebedouros",

    "aptidao_receptoras", "qtd_receptoras", "ecc", "vacinacao_dia",
    "acompanhamento_vet",

    "parecer_matrizes", "parecer_fiv", "observacoes_tecnico",
    "nome_tecnico", "cpf_tecnico",
]

# Rotulos (cabecalhos) legiveis para cada campo, usados na exportacao em Excel
FIELD_LABELS = {
    "nome_produtor": "Nome do Produtor",
    "cpf": "CPF",
    "data_nascimento": "Data de Nascimento",
    "telefone": "Telefone / Zap",
    "dap_caf": "DAP / CAF",
    "nome_propriedade": "Nome da Propriedade",
    "municipio": "Município",
    "comunidade": "Comunidade / Distrito",
    "car": "CAR",
    "latitude": "Latitude",
    "longitude": "Longitude",
    "assistido_ateg": "Assistido ATeG?",
    "tecnico_responsavel": "Técnico Responsável / Sindicato",
    "foto_produtor": "Foto do Produtor (arquivo)",
    "membros_residentes": "Membros Residentes no Lote (pessoas)",
    "sucessao_familiar": "Sucessão Familiar Identificada?",
    "mao_obra": "Mão de Obra na Pecuária",
    "fonte_renda": "Principal Fonte de Renda",
    "fonte_agua": "Fonte de Água Primária",
    "seguranca_hidrica": "Segurança Hídrica (Estiagem)",
    "area_leite": "Área Destinada ao Leite (ha)",
    "volume_diario": "Volume Diário Total (L/dia)",
    "vacas_lactacao": "Vacas em Lactação",
    "vacas_secas": "Vacas Secas",
    "novilhas": "Novilhas/Bezerras",
    "touros": "Touros/Garrotes",
    "produtividade_media": "Produtividade Média (L/vaca/dia)",
    "destino_producao": "Destino da Produção",
    "composicao_genetica": "Composição Genética",
    "grau_girolando": "Grau Girolando Predominante",
    "curral_ordenha": "Curral / Ordenha",
    "tipo_ordenha": "Tipo de Ordenha",
    "higiene_ordenha": "Higiene / Sanitização",
    "refrigeracao_leite": "Refrigeração do Leite",
    "capacidade_tanque": "Capacidade do Tanque (L)",
    "tronco_contencao": "Tronco de Contenção / Brete",
    "obs_infraestrutura": "Observações / Ajustes Necessários",
    "silagem": "Silagem (Milho/Sorgo)",
    "estoque_seca": "Estoque Estimado p/ Seca (meses)",
    "palma_forrageira": "Palma Forrageira",
    "area_palma": "Área Cultivada de Palma (ha/tarefas)",
    "capineira": "Capineira (Capiaçu/Outros)",
    "area_capineira": "Área de Capineira/Pasto (ha)",
    "suplementacao": "Suplementação Concentrada",
    "sal_mineral": "Sal Mineral Específico p/ Leite?",
    "agua_bebedouros": "Água Limpa e Abundante nos Bebedouros?",
    "aptidao_receptoras": "Possui Fêmeas Aptas como Receptoras?",
    "qtd_receptoras": "Qtd. Receptoras Estimadas Aptas (cabeças)",
    "ecc": "Escore de Condição Corporal (ECC)",
    "vacinacao_dia": "Vacinação Brucelose/Tuberculose em Dia?",
    "acompanhamento_vet": "Acompanhamento Vet. Reprodutivo Regular?",
    "parecer_matrizes": "Programa Matrizes do Amanhã",
    "parecer_fiv": "Projeto FIV Ceará",
    "observacoes_tecnico": "Observações / Recomendações Prioritárias do Técnico",
    "nome_tecnico": "Técnico Avaliador (Nome)",
    "cpf_tecnico": "CPF / Registro Profissional do Técnico",
}

# Lista dos 184 municípios do Ceará (ordem alfabética), usada no menu
# suspenso do campo "Município" para evitar erros de digitação.
MUNICIPIOS_CEARA = [
    "Abaiara", "Acarapé", "Acaraú", "Acopiara", "Aiuaba", "Alcântaras",
    "Altaneira", "Alto Santo", "Amontada", "Antonina do Norte", "Apuiarés",
    "Aquiraz", "Aracati", "Aracoiaba", "Ararendá", "Araripe", "Aratuba",
    "Arneiroz", "Assaré", "Aurora", "Baixio", "Banabuiú", "Barbalha",
    "Barreira", "Barro", "Barroquinha", "Baturité", "Beberibe", "Bela Cruz",
    "Boa Viagem", "Brejo Santo", "Camocim", "Campos Sales", "Canindé",
    "Capistrano", "Caridade", "Cariré", "Caririaçu", "Cariús", "Carnaubal",
    "Cascavel", "Catarina", "Catunda", "Caucaia", "Cedro", "Chaval",
    "Choró", "Chorozinho", "Coreaú", "Crateús", "Crato", "Croatá", "Cruz",
    "Deputado Irapuan Pinheiro", "Ererê", "Eusébio", "Farias Brito",
    "Forquilha", "Fortaleza", "Fortim", "Frecheirinha", "General Sampaio",
    "Graça", "Granja", "Granjeiro", "Groaíras", "Guaiúba",
    "Guaraciaba do Norte", "Guaramiranga", "Hidrolândia", "Horizonte",
    "Ibaretama", "Ibiapina", "Ibicuitinga", "Icapuí", "Icó", "Iguatu",
    "Independência", "Ipaporanga", "Ipaumirim", "Ipu", "Ipueiras",
    "Iracema", "Irauçuba", "Itaiçaba", "Itaitinga", "Itapajé", "Itapipoca",
    "Itapiúna", "Itarema", "Itatira", "Jaguaretama", "Jaguaribara",
    "Jaguaribe", "Jaguaruana", "Jardim", "Jati", "Jijoca de Jericoacoara",
    "Juazeiro do Norte", "Jucás", "Lavras da Mangabeira",
    "Limoeiro do Norte", "Madalena", "Maracanaú", "Maranguape", "Marco",
    "Martinópole", "Massapê", "Mauriti", "Meruoca", "Milagres", "Milhã",
    "Miraíma", "Missão Velha", "Mombaça", "Monsenhor Tabosa",
    "Morada Nova", "Moraújo", "Morrinhos", "Mucambo", "Mulungu",
    "Nova Olinda", "Nova Russas", "Novo Oriente", "Ocara", "Orós",
    "Pacajus", "Pacatuba", "Pacoti", "Pacujá", "Palhano", "Palmácia",
    "Paracuru", "Paraipaba", "Parambu", "Paramoti", "Pedra Branca",
    "Penaforte", "Pentecoste", "Pereiro", "Pindoretama", "Piquet Carneiro",
    "Pires Ferreira", "Poranga", "Porteiras", "Potengi", "Potiretama",
    "Quiterianópolis", "Quixadá", "Quixelô", "Quixeramobim", "Quixeré",
    "Redenção", "Reriutaba", "Russas", "Saboeiro", "Salitre",
    "Santana do Acaraú", "Santana do Cariri", "Santa Quitéria",
    "São Benedito", "São Gonçalo do Amarante", "São João do Jaguaribe",
    "São Luís do Curu", "Senador Pompeu", "Senador Sá", "Sobral",
    "Solonópole", "Tabuleiro do Norte", "Tamboril", "Tarrafas", "Tauá",
    "Tejuçuoca", "Tianguá", "Trairi", "Tururu", "Ubajara", "Umari",
    "Umirim", "Uruburetama", "Uruoca", "Varjota", "Várzea Alegre",
    "Viçosa do Ceará",
]

